### ISSUE TITLE
"TypeError: an integer is required"

### ISSUE THREAD

**Issue by rugk** [muflone/gespeaker#61]
```console
$ gespeaker                                         
loading available plugins...
[DBUS]: init plugin v.0.2
[Debug]: init plugin v.0.2
[Debug]: __init__("Debug", "0.2", "Fabio Castelli", "Debug interface", "/usr/share/gespeaker/plugins/plugin_debug/icon.svg", "")
[Stop on quit]: init plugin v.0.1
[Save voice settings]: init plugin v.0.1
[Welcome message]: init plugin v.0.1
[Save window position]: init plugin v.0.1
[Save window size]: init plugin v.0.1
starting gespeaker
python version detected: 2.7
loading interface from /usr/share/gespeaker/data/ui/gespeaker.glade
loading controls from UI
loading languages from /usr/bin/espeak --voices
Traceback (most recent call last):
  File "gespeaker.py", line 48, in <module>
    main = gespeakerUI.gespeakerUI()
  File "/usr/share/gespeaker/src/gespeakerUI.py", line 106, in __init__
    self.loadSettings(True)
  File "/usr/share/gespeaker/src/gespeakerUI.py", line 198, in loadSettings
    self.cboLanguages.set_active(self.defaultLanguageIndex)
TypeError: an integer is required
$ apt-cache show gespeaker 
Package: gespeaker
Version: 0.8.5-1
Installed-Size: 535
Maintainer: Fabio Castelli <muflone@vbsimple.net>
Architecture: all
Depends: alsa-utils | pulseaudio-utils, espeak, espeak-data, librsvg2-common, python-glade2, python-gobject, python-gtk2, python-xdg, python:any (>= 2.6.6-7~)
Suggests: mbrola
Description-en: GTK+ front-end for eSpeak and mbrola
 Gespeaker is a GTK+ frontend for eSpeak and mbrola.
 It allows one to play a text in many languages with settings
 for voice, pitch, volume, speed and word gap.
 .
 Since version 0.6 it can use mbrola package and voices to
 obtain a more realistic text reading experience.
Description-md5: c0f49e1362818bdd4cdda2a9b9b9225c
Homepage: http://www.muflone.com/gespeaker/
Tag: accessibility::speech, implemented-in::python, interface::x11,
 role::program, scope::application, sound::speech, uitoolkit::gtk,
 use::entertaining, works-with::audio, works-with::text,
 x11::application
Section: sound
Priority: optional
Filename: pool/main/g/gespeaker/gespeaker_0.8.5-1_all.deb
Size: 122262
MD5sum: 4b8301fba3577324ba5b77737674e261
SHA1: bc472ed5f488329fd27ee07cec4ee1d45f22c0bc
SHA256: 5d761f5d02201525dbfd06be3fab985615e89859b6e0ba67ac11266225f9e198
```

This prevents it from starting here. Installed from Debian repositories.

**Comment by muflone** [comment]
Hi

It seems there's some bad configuration in your home folder.
Please try to delete the ~/.configu/gespeaker (or ~/.gespeaker) folder and start the application again.

**Comment by rugk** [comment]
I just had installed it from the Debian repo. But I'll try your suggestion.

**Comment by muflone** [comment]
What language are you using?
please show me also your locale with echo $LANG

**Comment by rugk** [comment]
```shell
$ echo $LANG
de_DE.utf8
```

Removing `~/.config/gespeaker` (the uconfig version does not exist) and `~/.gespeaker` does not help. The next restart still shows:
```shell
$ gespeaker
loading available plugins...
[DBUS]: init plugin v.0.2
[Debug]: init plugin v.0.2
[Debug]: __init__("Debug", "0.2", "Fabio Castelli", "Debug interface", "/usr/share/gespeaker/plugins/plugin_debug/icon.svg", "")
[Stop on quit]: init plugin v.0.1
[Save voice settings]: init plugin v.0.1
[Welcome message]: init plugin v.0.1
[Save window position]: init plugin v.0.1
[Save window size]: init plugin v.0.1
starting gespeaker
python version detected: 2.7
loading interface from /usr/share/gespeaker/data/ui/gespeaker.glade
loading controls from UI
loading languages from /usr/bin/espeak --voices
Traceback (most recent call last):
  File "gespeaker.py", line 48, in <module>
    main = gespeakerUI.gespeakerUI()
  File "/usr/share/gespeaker/src/gespeakerUI.py", line 106, in __init__
    self.loadSettings(True)
  File "/usr/share/gespeaker/src/gespeakerUI.py", line 198, in loadSettings
    self.cboLanguages.set_active(self.defaultLanguageIndex)
TypeError: an integer is required
```

**Comment by muflone** [comment]
Ok, that's an old issue, still present in Debian, I have to update the package in the Debian repositories.

You have two ways to fix your issue:

a) Install the latest Gespeaker version (0.8.6)
http://www.muflone.com/gespeaker/english/download.html#tabs|Tabs_Group_name:Tab_v086

b) Start Gespeaker once with english language and it will fix your configuration file and then the German language won't have issues:
    rm -rf "~/.config/gespeaker"
    LANG=C gespeaker
Then close gespeaker and you'll be able to start it again normally

**Comment by rugk** [comment]
Yes, it works! Thanks for your help.

**Comment by pilloutche** [comment]
Hello, i am experiencing the same problem in ubuntu 18.04LTS (relatively new installation) and can't find out what is the problem...

```
$ gspeaker
loading available plugins...
[DBUS]: init plugin v.0.2
[Debug]: init plugin v.0.2
[Debug]: __init__("Debug", "0.2", "Fabio Castelli", "Debug interface", "/usr/share/gespeaker/plugins/plugin_debug/icon.svg", "")
[Stop on quit]: init plugin v.0.1
[Save voice settings]: init plugin v.0.1
[Welcome message]: init plugin v.0.1
[Save window position]: init plugin v.0.1
[Save window size]: init plugin v.0.1
starting gespeaker
python version detected: 2.7
loading interface from /usr/share/gespeaker/data/ui/gespeaker.glade
loading controls from UI
loading languages from /usr/bin/espeak --voices
default language "english" not found in the languages list, fallback to "default"
Traceback (most recent call last):
  File "gespeaker.py", line 48, in <module>
    main = gespeakerUI.gespeakerUI()
  File "/usr/share/gespeaker/src/gespeakerUI.py", line 106, in __init__
    self.loadSettings(True)
  File "/usr/share/gespeaker/src/gespeakerUI.py", line 204, in loadSettings
    self.cboLanguages.set_active(self.defaultLanguageIndex)
TypeError: an integer is required
```
my language setup seems correct.
```
$echo $LANG
en_US.UTF-8

```
the rm command and changing variable environment LANG doesn't worked for me.

I've installed the version gespeaker 0.8.6-1 (first using ubuntu gui and secondly using "git" with 0.8.6 tag and build)

any idea ? what's the problem about lang variable integer ?

thank's in advance for any reply !
